version: 2

run:
  timeout: 3m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gocritic
    - ineffassign
    - dupl
    - misspell
    - gosec
    - gocyclo

linters-settings:
  gocyclo:
    min-complexity: 15

  dupl:
    threshold: 150

  revive:
    rules:
      - name: exported
      - name: var-naming
      - name: indent-error-flow
      - name: error-return

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl

    - path: internal/infra/logger.go
      linters:
        - gosec
